# docker command 
sudo docker run --rm -v ~/Chaste/Build/:/home/chaste/build -v ~/Chaste/Output/:/home/chaste/testoutput chaste/base build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationPde -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 1e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -psproutfunctiontestnb 1 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 0.75 -thresholdlength 2.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DPde/CoupledModel2DPdeSeed10Source5 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DAnalyticalApproxPde/Test6/CoupledModel2DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DConstant/Test6/CoupledModel2DConstantSeed10Source5 -output_directory_twolesions PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DTwoLesions/CoupledModel2DConstantSeed10Sources5 

# singularity for two lesions command 
singularity exec --bind /hpc/coli171/Results:/home/chaste/testoutput /people/coli171/Containers/base_latest.sif /people/coli171/Chaste/Build/projects/AngiogenesisModel/test/TestAngiogenesisModelTwoLesions -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 1e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.5 -S 1e-5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -psproutfunctiontestnb 1 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 0.75 -thresholdlength 5.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DPde/CoupledModel2DPdeSeed10Source5 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DAnalyticalApproxPde/Test6/CoupledModel2DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DConstant/Test6/CoupledModel2DConstantSeed10Source5 -output_directory_twolesions PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DTwoLesions/CoupledModel2DConstantSeed10Sources5 

# singularity for steady-state 
singularity exec --bind /hpc/coli171/Results:/home/chaste/testoutput /people/coli171/Containers/base_latest.sif /people/coli171/Chaste/Build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationAnalyticalApproximationOfPde -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 0.44e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 1.0 -vegfconstantbackground 0.1 -S 1e-5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -psproutfunctiontestnb 1 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 1.5 -thresholdlength 5.0 -time 2000 -seed 20 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DPde/CoupledModel2DPdeSeed20Source10 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DAnalyticalApproxPdeJuly2025/Test17/CoupledModel2DAnalyticalApproxPdeSeed20Source10 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DConstantJuly2025/Test17/CoupledModel2DConstantSeed20Source10 -output_directory_twolesions PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DTwoLesions/CoupledModel2DConstantSeed20Sources10

# singularity for constant 
singularity exec --bind /hpc/coli171/Results:/home/chaste/testoutput /people/coli171/Containers/base_latest.sif /people/coli171/Chaste/Build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationConstant -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 0.44e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.5 -S 1e-5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -psproutfunctiontestnb 1 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 1.5 -thresholdlength 5.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DPde/CoupledModel2DPdeSeed10Source5 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DAnalyticalApproxPdeAugust2025/Test1/CoupledModel2DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DConstantAugust2025/Test1/CoupledModel2DConstantSeed10Source5 -output_directory_twolesions PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DTwoLesions/CoupledModel2DConstantSeed10Sources5 

# singularity for PDE 
singularity exec --bind /hpc/coli171/Results:/home/chaste/testoutput /people/coli171/Containers/base_latest.sif /people/coli171/Chaste/Build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationPde -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 0.44e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.5 -S 1e-5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -psproutfunctiontestnb 1 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 1.5 -thresholdlength 5.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DPde/TestConvergenceTime/CoupledModel2DPdeSeed10Source5 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DAnalyticalApproxPdeAugust2025/Test1/CoupledModel2DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DConstantAugust2025/Test1/CoupledModel2DConstantSeed10Source5 -output_directory_twolesions PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DTwoLesions/CoupledModel2DConstantSeed10Sources5 