# docker command 
sudo docker run --rm -v ~/Chaste/Build/:/home/chaste/build -v ~/Chaste/Output/:/home/chaste/testoutput chaste/base build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationPde -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 1e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -psproutfunctiontestnb 1 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 1.5 -thresholdlength 5.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DPde/CoupledModel2DPdeSeed10Source5 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DAnalyticalApproxPde/Test6/CoupledModel2DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DConstant/Test6/CoupledModel2DConstantSeed10Source5 -output_directory_twolesions PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DTwoLesions/CoupledModel2DConstantSeed10Sources5 

# singularity for steady-state (currently in 3D)
singularity exec --bind /hpc/coli171/Results:/home/chaste/testoutput /people/coli171/Containers/base_latest.sif /people/coli171/Chaste/Build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationAnalyticalApproximationOfPde -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 0.44e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.1 -S 1e-5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 1.5 -thresholdlength 5.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis3D/CoupledModel3DPde/CoupledModel3DPdeSeed10Source5 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis3D/CoupledModel3DAnalyticalApproxPde/CoupledModel3DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis3D/CoupledModel3DConstant/CoupledModel3DConstantSeed10Source5

# singularity for constant (currently in 3D)
singularity exec --bind /hpc/coli171/Results:/home/chaste/testoutput /people/coli171/Containers/base_latest.sif /people/coli171/Chaste/Build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationConstant -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 0.44e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 1.0 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.5 -S 1e-5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 1.5 -thresholdlength 5.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis3D/CoupledModel3DPde/CoupledModel3DPdeSeed10Source5 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis3D/CoupledModel3DAnalyticalApproxPde/CoupledModel3DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis3D/CoupledModel3DConstant/CoupledModel3DConstantSeed10Source5

# singularity for PDE 
singularity exec --bind /hpc/coli171/Results:/home/chaste/testoutput /people/coli171/Containers/base_latest.sif /people/coli171/Chaste/Build/projects/AngiogenesisModel/test/TestAngiogenesisModelWithVegfConcentrationPde -vegfdudtcoeff 0.1 -vegfdiffusioncoeff 0.44e4 -vegfdecaycoeff 1.0 -vegfcreationcoeff 0.0 -vegfconsumptioncoeff 0.1 -vegfinitialvalue 0.1 -vegfboundaryvalue 0.5 -vegfconstantbackground 0.1 -S 1e-5 -sigma 1e-1 -chi 1e-4 -omegap 1e-1 -omegaa 1e-5 -maxsproutingrate 0.08 -cmax 0.8 -cmin 0.3 -pmax 0.98 -pmin 0.5 -anastomosislength 1.5 -thresholdlength 5.0 -time 2000 -seed 10 -output_directory PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DPde/TestMeshSize/CoupledModel2DPdeSeed10Source5Test4 -output_directory_analyticalapproxvegf PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DAnalyticalApproxPde/CoupledModel2DAnalyticalApproxPdeSeed10Source5 -output_directory_vegfconstant PaperAngiogenesisModel2025/PaperModel2025Analysis2D/CoupledModel2DConstant/CoupledModel2DConstantSeed10Source5 